package excecoes;

public class ExercicieTwo {

	public static void main(String[] args) {
		int numerador = 0;
		int denominador = 10;
		
		try {
			int resultado = numerador / denominador;
			System.out.println("Deu erro: " + resultado);
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
}
